heat_template_version: 2018-08-31

description: > 
    This template instantiates a basic VM.

parameters:
    user_key:
        type: string
        label: ssh_user_key
        description: Public user ssh key to be injected in the cluster VMs
        constraints:
            - custom_constraint: nova.keypair
    vm_flavour:
        type: string
        label: vm_flavour
        description: Flavour for the VM
        constraints:
            - custom_constraint: nova.flavor
    vm_image:
        type: string
        label: vm_image
        description: Required VM image
        constraints:
            - custom_constraint: glance.image
    user_network:
        type: string
        label: user_network
        description: Add the required VM network
        constraints:
            - custom_constraint: neutron.network

resources:
    my_server:
        type: OS::Nova::Server
        properties:
          name: MyServer
          metadata:
              # Some metadata examples to be included in the VM
              server: master
              color: red
          security_groups: 
              - default
          networks: 
              - network: { get_param: user_network }
                tag: master_ip
          key_name: { get_param: user_key }
          image: { get_param: vm_image }
          flavor: { get_param: vm_flavour }

