heat_template_version: 2018-08-31

description: >
    This Heat template creates a new security group and
    assigns it to a new instantiated VM.

parameters:
    user_key:
        type: string
        label: ssh_user_key
        description: Public user ssh key to be injected in the cluster VMs
        constraints:
            - custom_constraint: nova.keypair
    vm_flavour:
        type: string
        label: vm_flavour
        description: Flavour for the VM
        constraints:
            - custom_constraint: nova.flavor
    vm_image:
        type: string
        label: vm_image
        description: Required VM image
        constraints:
            - custom_constraint: glance.image
    user_network:
        type: string
        label: user_network
        description: Add the required VM network
        constraints:
            - custom_constraint: neutron.network

resources: 
  SecurityGroup_1: 
    type: "OS::Neutron::SecurityGroup"
    properties: 
      rules: 
        - direction: ingress
          ethertype: IPv4
          protocol: tcp
          remote_mode: remote_ip_prefix
          # Allow any connection from outside to port 8080
          remote_ip_prefix: "0.0.0.0/0"
          port_range_max: 8080
          port_range_min: 8080
      name: my_firewall
      description: "This is my personal firewall for port 8080"

  Server_1: 
    type: "OS::Nova::Server"
    properties: 
      security_groups: 
        # We can assign several security groups to our VMs
        - default
        - { get_resource: SecurityGroup_1 }
      networks: 
        - network: { get_param: user_network }
      name: My_server_00
      key_name: { get_param: user_key }
      image: { get_param: vm_image }
      flavor: { get_param: vm_flavour }
