heat_template_version: 2018-03-02

description: > 
    This template illustrates the creation of a VM
    together with ansible post running script
parameters:
    user_key:
        type: string
        label: ssh_user_key
        description: Public user ssh key to be injected in the cluster VMs
        constraints:
            - custom_constraint: nova.keypair
    user_net:
        type: string
        label: user_net
        description: Add the required VM network
        constraints:
            - custom_constraint: neutron.network
    user_vm_flavor:
        type: string
        label: vm_flavor
        description: Choose a flavor
        constraints:
            - custom_constraint: nova.flavor
        default: m1.small
    user_vm_image:
        type: string
        label: vm_image
        description: Choose an image
        constraints:
            - custom_constraint: glance.image
    ansible_playbook_url:
        type: string
        label: ansible_playbook_url
        description: Set ansible playbook URL location

resources:
    wait_condition:
        type: OS::Heat::WaitCondition
        properties:
            handle: {get_resource: wait_handle}
            count: 1
            timeout: 600

    wait_handle:
        type: OS::Heat::WaitConditionHandle

    my_server:
        type: OS::Nova::Server
        properties:
            name: MyVM
            metadata:
                # Some metadata examples to be included in the VM
                server: master
                color: red
            security_groups: 
                - default
            networks: 
                - network: { get_param: user_net }
                  tag: master_ip
            key_name: { get_param: user_key }
            image: { get_param: user_vm_image }
            flavor: { get_param: user_vm_flavor }
            user_data_format: RAW
            user_data:
              str_replace:
                template: { get_file: 'https://raw.githubusercontent.com/hpcugent/openstack-templates/master/heat/scripts/run_ansible.sh' }
                params:
                  wc_notify: { get_attr: [wait_handle, curl_cli] }
                  __ANSIBLE_URL__: { get_param: ansible_playbook_url }
