heat_template_version: 2018-03-02

description: > 
    This template creates a persistent bootable volumen
    from a existing image (selected by the user).
    After that Heat starts a VM using the new persistent volume.

parameters:
    user_key:
        type: string
        label: ssh_user_key
        description: Public user ssh key to be injected in the VM
        constraints:
            - custom_constraint: nova.keypair
    vm_flavour:
        type: string
        label: vm_flavour
        description: Flavour for the VM
        constraints:
            - custom_constraint: nova.flavor
    os_image:
        type: string
        label: os_image
        description: Choose an OpenStack image from the list
        constraints:
            - custom_constraint: glance.image
    user_network:
        type: string
        label: user_network
        description: Add the required VM network
        constraints:
            - custom_constraint: neutron.network
    user_volume_size:
        type: number
        label: user_volume_size
        default: 10
        description: Volume size in GB
        constraints:
            - range: { min: 10, max: 50 }
              description: Volume size GB
            - modulo: { step: 1, offset: 0 }

resources:
    my_bootable_volume:
        type: OS::Cinder::Volume
        # Here we create a persisten volume from a existing image
        properties:
            size: { get_param: user_volume_size }
            image: { get_param: os_image }
    my_server:
        type: OS::Nova::Server
        depends_on:
          - my_bootable_volume
        properties:
          name: MyServer
          block_device_mapping:
              - device_name: vda
                volume_id: { get_resource: my_bootable_volume }
                delete_on_termination: false
          metadata:
              # Some metadata examples to be included in the VM
              server: master
              color: red
              boot_volume_id: { get_resource: my_bootable_volume }
          security_groups: 
              - default
          networks: 
              - network: { get_param: user_network }
                tag: master_ip
          key_name: { get_param: user_key }
          flavor: { get_param: vm_flavour }

