- name: "Resize {{device}}"
  hosts: all
  tasks:
  - name: CreateOrResize
    community.general.filesystem:
      fstype: "{{ filesystem }}"
      dev: "{{ device }}"
      resizefs: true
    become: true
    timeout: 60