- name: Configure Nginx
  connection: local
  hosts: localhost
  tasks:
   - name: "{{ (install == 'true') | ternary('Install','Uninstall')}} Nginx"
     package: name=nginx state="{{ 'present' if install == 'true' else 'absent' }}"
     notify:
      - Start Nginx
  handlers:
   - name: Start Nginx
     service: name=nginx state="{{ 'started' if install == 'true' else 'stopped' }}"
     when: install
