- name: Configure NFS mount
  hosts: all
  tasks:
  - name: NFS
    ansible.posix.mount:
      path: /mnt/nfs
      src: "{{ nfs_path }}"
      fstype: nfs
      opts: defaults,_netdev
      state: "{{ 'mounted' if mount == 'true' else 'absent' }}"
  become: true
  timeout: 120
