#cloud-config
packages:
  - curl
  - jq
  - nfs-common

# write_files:
# %{ for file in files }
# - encoding: b64
#   content: ${ file.content_base64 }
#   owner: root:root
#   path: /opt/vsc/ansible/${basename(file.filename)}
#   permissions: '0770'
# %{ endfor }
# - content: |
#     [defaults]
#     localhost_warning=False
#     collections_on_ansible_version_mismatch=ignore

#     [inventory]
#     inventory_unparsed_warning=False
#   path: /etc/ansible/ansible.cfg
runcmd:
- [mkdir,-p,/opt/vsc/cron]
- [mkdir,-p,/opt/vsc/cron/]

# - ["ansible-galaxy", "collection", "install", "ansible.posix"]
# - ["ansible-galaxy", "collection", "install", "community.general"]
