---
- name: Install and run Nginx
  connection: local
  hosts: localhost
  tasks:
   - name: Install Nginx
     package: name=nginx state=installed
     notify:
      - Start Nginx
  handlers:
   - name: Start Nginx
     service: name=nginx state=started
